# Site settings
title: Commande-Online.fr SAS API
tag_text: Commande-Online.fr SAS API
description: Description of Commande-Online.fr SAS API
url: "http://commande-online.github.io/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
